import { execa } from "execa";
import {
  fetchOpenOacPRs,
  findOacPRByTitle,
  findOacPRForIssue,
} from "../../../core/github-pr-cache.js";
import type { Task } from "../../../core/index.js";
import type { ExecutionOutcome, SandboxInfo, TaskRunResult } from "./types.js";
import { PR_CREATION_TIMEOUT_MS } from "./types.js";

const OAC_PR_TITLE_PREFIX = "[OAC]";

export async function createPullRequest(input: {
  task: Task;
  execution: ExecutionOutcome;
  sandbox?: SandboxInfo;
  repoFullName: string;
  baseBranch: string;
  ghToken?: string;
}): Promise<TaskRunResult["pr"] | undefined> {
  if (!input.sandbox) {
    return undefined;
  }

  // Guard: never create a PR with 0 real file changes
  const realFiles = input.execution.filesChanged.filter((f) => !f.startsWith(".oac/"));
  if (realFiles.length === 0) {
    console.warn(`[oac] PR creation blocked: 0 real files changed for "${input.task.title}".`);
    return undefined;
  }

  const { branchName, sandboxPath } = input.sandbox;

  try {
    const ghEnv = buildGhEnv(input.ghToken);

    // Pre-PR guard: check for duplicate OAC PRs (single API call for both checks)
    if (input.ghToken) {
      const oacPRs = await fetchOpenOacPRs(input.repoFullName, input.ghToken);

      if (input.task.linkedIssue) {
        const duplicate = findOacPRForIssue(oacPRs, input.task.linkedIssue.number);
        if (duplicate) {
          console.warn(
            `[oac] Skipping PR: existing OAC PR #${duplicate} already targets issue #${input.task.linkedIssue.number}`,
          );
          return undefined;
        }
      } else {
        const prTitle = `${OAC_PR_TITLE_PREFIX} ${input.task.title}`;
        const duplicate = findOacPRByTitle(oacPRs, prTitle);
        if (duplicate) {
          console.warn(
            `[oac] Skipping PR: existing OAC PR #${duplicate} already has title "${prTitle}"`,
          );
          return undefined;
        }
      }
    }

    const pushed = await pushBranchFromSandbox(input.sandbox, ghEnv);
    if (!pushed) {
      return undefined;
    }

    // Create PR using gh CLI
    const prTitle = `[OAC] ${input.task.title}`;
    const prBodyLines = [
      "## Summary",
      "",
      input.task.description || `Automated contribution for task "${input.task.title}".`,
      "",
    ];

    // Auto-resolve: link PR to GitHub issue so it closes on merge
    if (input.task.linkedIssue) {
      prBodyLines.push(`Closes #${input.task.linkedIssue.number}`, "");
    }

    prBodyLines.push(
      "## Context",
      "",
      `- **Task source:** ${input.task.source}`,
      `- **Complexity:** ${input.task.complexity}`,
      `- **Tokens used:** ${input.execution.totalTokensUsed}`,
      `- **Files changed:** ${input.execution.filesChanged.length}`,
    );

    if (input.task.linkedIssue) {
      prBodyLines.push(`- **Resolves:** #${input.task.linkedIssue.number}`);
    }

    const contextAck = readContextAck(input.task);
    if (contextAck) {
      prBodyLines.push("", "## Repository Policy Acknowledgement", "");
      prBodyLines.push("- **Context files read:**");
      for (const file of contextAck.files.slice(0, 5)) {
        prBodyLines.push(`  - \`${file}\``);
      }
      if (contextAck.summary.length > 0) {
        prBodyLines.push("", "- **Policy summary used:**");
        for (const line of contextAck.summary.slice(0, 5)) {
          prBodyLines.push(`  - ${line}`);
        }
      }
      if (contextAck.digest) {
        prBodyLines.push("", `- **Context digest:** \`${contextAck.digest}\``);
      }
    }

    prBodyLines.push(
      "",
      "---",
      "*This PR was automatically generated by [OAC](https://github.com/Open330/open-agent-contribution).*",
    );

    const prBody = prBodyLines.join("\n");

    const ghResult = await execa(
      "gh",
      [
        "pr",
        "create",
        "--repo",
        input.repoFullName,
        "--title",
        prTitle,
        "--body",
        prBody,
        "--head",
        branchName,
        "--base",
        input.baseBranch,
      ],
      { cwd: sandboxPath, env: ghEnv, timeout: PR_CREATION_TIMEOUT_MS },
    );

    // Parse PR URL from gh output
    const prUrl = ghResult.stdout.trim();
    const prNumberMatch = prUrl.match(/\/pull\/(\d+)/);
    const prNumber = prNumberMatch ? Number.parseInt(prNumberMatch[1], 10) : 0;

    return {
      number: prNumber,
      url: prUrl,
      status: "open",
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.warn(`[oac] PR creation failed: ${message}`);
    return undefined;
  }
}

export async function pushBranchOnly(input: {
  sandbox?: SandboxInfo;
  ghToken?: string;
}): Promise<boolean> {
  if (!input.sandbox) {
    return false;
  }

  const ghEnv = buildGhEnv(input.ghToken);
  return await pushBranchFromSandbox(input.sandbox, ghEnv);
}

function buildGhEnv(ghToken: string | undefined): Record<string, string> {
  const ghEnv: Record<string, string> = { ...process.env } as Record<string, string>;
  if (ghToken) {
    ghEnv.GH_TOKEN = ghToken;
    ghEnv.GITHUB_TOKEN = ghToken;
  }
  return ghEnv;
}

async function pushBranchFromSandbox(
  sandbox: SandboxInfo,
  ghEnv: Record<string, string>,
): Promise<boolean> {
  try {
    await execa("git", ["push", "--set-upstream", "origin", sandbox.branchName], {
      cwd: sandbox.sandboxPath,
      env: ghEnv,
      timeout: PR_CREATION_TIMEOUT_MS,
    });
    return true;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.warn(`[oac] Branch push failed: ${message}`);
    return false;
  }
}

function readContextAck(task: Task):
  | {
      files: string[];
      summary: string[];
      digest?: string;
    }
  | undefined {
  if (!task.metadata || typeof task.metadata !== "object" || task.metadata === null) {
    return undefined;
  }
  const raw = (task.metadata as Record<string, unknown>).contextAck;
  if (!raw || typeof raw !== "object") return undefined;
  const record = raw as Record<string, unknown>;

  const files = Array.isArray(record.files)
    ? record.files.filter(
        (item): item is string => typeof item === "string" && item.trim().length > 0,
      )
    : [];
  if (files.length === 0) return undefined;

  const summary = Array.isArray(record.summary)
    ? record.summary.filter(
        (item): item is string => typeof item === "string" && item.trim().length > 0,
      )
    : [];
  const digest =
    typeof record.digest === "string" && record.digest.trim().length > 0
      ? record.digest
      : undefined;
  return { files, summary, digest };
}

