name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the fields below so we can understand your proposal.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is this feature related to a problem? Describe the issue you are trying to solve.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution or feature you would like to see.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you have considered...
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: Which area does this feature relate to?
      options:
        - Core library
        - CLI / tooling
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples that support the request.
      placeholder: Add any other context here...
    validations:
      required: false
